### ISSUE TITLE
Check for woody species only

### ISSUE THREAD

**Issue by danfbflynn** [danfbflynn/ospree#12]
Eg heide01 is sedum

lyndon77 silene

nerd95 opuntia

Fragaria studies:
heide07
heide77
kronenberg76
lieten97
smeets80
smeets82
sonsteby09a
sonsteby09b
verheul07
voipio01

**Comment by ejforrestel** [comment]
there was also some cactus in there! can you take me off all these chains, dan? thanks! :)

**Comment by danfbflynn** [comment]
made a 'woody' column in data_detailed
