### ISSUE TITLE
Okie 2011

### ISSUE THREAD

**Issue by lizzieinvancouver** [danfbflynn/ospree#2]
Couple extra notes:

“All tests used excised twigs of the previous season’s upright growth, basally trimmed to 􏰁30 cm length, with a basal diameter of 􏰁4 to 5 mm.”

Seedlings planted in 2002

Answers to your query:

Light vs. dark experiment: In 2006–2007, starting cut dates (and bcu accu- mulations) were: ‘Flordaprince’, 9 Nov. (122 bcu); ‘Flordadawn’, 23 Nov. (272 bcu); and ‘Juneprince’ and ‘Sunland’, 25 Jan. (798 bcu). 

In 2007–2008, starting cut dates were ‘Flordaprince’, 16 Nov. (90 bcu); ‘Florda- dawn’, 30 Nov. (187 bcu); ‘Juneprince’, 28 Dec. (442 bcu); and ’Sunland’, 18 Jan. (614 bcu). Cut twigs went directly from the field into the forcing chambers. In 2008–2009, ‘Sunland’ cuttings were taken on 2 Jan. (543 bcu) and given 4, 8, or 12 d chilling in the dark at 4 °C and then moved to the forcing chamber.

**Comment by danfbflynn** [comment]
Added to fieldsample date
