### ISSUE TITLE
non-numeric chilldays

### ISSUE THREAD

**Issue by AileneKane** [danfbflynn/ospree#26]
check the chilldays column- there are many non-numeric values there that may be useful (e.g. ""mean of 39, 55, 67, 98, 111" , "1996-11-15", "50 degreedays"). they are currently excluded from the experimental chilling calculations in Field_Exp_Chilling_Calc.R

**Comment by AileneKane** [comment]
I added a file that summarizes the studies/papers and values that need to be checked here:
https://github.com/danfbflynn/ospree/blob/master/input/chilldaystempstocheck.csv

**Comment by danfbflynn** [comment]
Duplicate issue
