### ISSUE TITLE
Campbell 1975

### ISSUE THREAD

**Issue by lizzieinvancouver** [danfbflynn/ospree#3]
- series of studies with dates but no year given …

these are a series of provenance trials with seeds started in the greenhouse (March), moved to  the lathehouse in May .. then studies start.

I get the feeling the studies happened across years, e.g. “Treatments usually started in September after all seedlings had set buds and ended on the dat of bud flushing’

So I am not sure we need the year —> No field chilling?

**Comment by danfbflynn** [comment]
Used 1973 as year, and 1973-09-01 as field sample date
