### ISSUE TITLE
daystobudset

### ISSUE THREAD

**Issue by lizzieinvancouver** [danfbflynn/ospree#33]
in clean_respvar.R Jehane renamed:

scrapedata$respvar[scrapedata$respvar == "daystobudset"] <- "daystobudburst"
scrapedata$respvar[scrapedata$respvar == "baystobudset"] <- "daystobudburst"

We should double-check that these are budburst and not budset!

**Comment by danfbflynn** [comment]
None left in the ospree; only percentbudset in viheraaarnio06
