### ISSUE TITLE
Method to flag studies with multiple respvars that are same under respvar.simple?

### ISSUE THREAD

**Issue by lizzieinvancouver** [danfbflynn/ospree#34]
I created a new column to try to get similar response variables together -- respvar.simple, but we should be careful to know when:
- a study measures more than 1 respvar that is the same type of respvar.simple
- a study measures more than 1 respvar and each is a different type of respvar.simple

**Comment by danfbflynn** [comment]
Made two new columns:

`multiresp`: multiple original `respvar` which are now all one `respvar.simple`

`multibothresp`: multiple original `respvar` which each are a different `respvar.simple`
